tmax-cloud/cicd-operator

api/v1/integrationjob_types.go, api/v1/job_labels.go, docs/integrationJob.md, docs/modules/scheduler.md, main.go, pkg/pipelinemanager/pipelinemanager.go, pkg/scheduler/fifo.go, pkg/scheduler/scheduler.go
Initial implementation of FIFO scheduler (from `IntegrationJob` to `PipelineRun`)
- Mainly a part of #8
- Also affects #9
=> [feat] Implement scheduler

.github/workflows/main.yaml
Added test_crd test for github workflow.
It was in Makefile but not in GitHub workflow
=> [ci] Add CRD generation test

main.go, pkg/dispatcher/dispatcher.go, pkg/webhook/handler_webhook.go, pkg/webhook/plugin.go
Added plugin, which works as webhook handlers.
Also, added skeleton for dispatcher as an example of webhook plugins.
close #5
=> [feat] Implement webhook handler

pkg/git/github/github.go
- Added logic to check status code for the api call
- Added explicit error-returning logics
=> [fix] Add error handling logic for github webhook registration

api/v1/integrationconfig_types.go, api/v1/job_labels.go, api/v1/job_types.go, config/crd/bases/cicd.tmax.io_integrationconfigs.yaml, config/crd/bases/cicd.tmax.io_integrationjobs.yaml, pkg/pipelinemanager/env.go, pkg/pipelinemanager/pipelinemanager.go, pkg/pipelinemanager/step_git_checkout.go
Pipeline generator (a part of pipeline manager) converts IntegrationJobs
into PipelineRuns.
Generator only makes object (not create/apply to cluster)
#9
=> [feat] Implement pipeline generator

Makefile, api/v1/git_types.go, api/v1/integrationconfig_types.go, config/manager/manager.yaml, controllers/ingress_controller.go, controllers/integrationconfig_controller.go, go.mod, go.sum, internal/utils/k8s.go, internal/utils/rand.go, internal/utils/utils.go, main.go
- Add IntegrationConfig controller which generates secrets and registers
webhook
- Add Ingress controller which watches ingress and set external hostname
referring to the ingress hostname
=> [feat] Implement IntegrationConfig controller

config/report/configMap.yaml, config/samples/cicd_v1_integrationconfig.yaml, config/samples/cicd_v1_integrationjob.yaml, config/samples/kustomization.yaml, main.go, pkg/pipelinemanager/pipelinemanager.go, pkg/server/handler_report.go, pkg/server/handler_webhook.go, pkg/server/plugin.go, pkg/server/server.go
- Report is used for commit status detail page (#12)
=> [feat] Add report server implementation

pkg/git/github/github.go, pkg/git/gitlab/gitlab.go
- It is meant to reduce error log
=> [fix] Fix to return nil when webhook receives unsupported events

pkg/git/github/github.go, pkg/git/gitlab/gitlab.go, pkg/git/http.go
=> [refactor] Functionize HTTP api calls for git client

pkg/pipelinemanager/pipelinemanager.go
=> [feat] Reflect custom tasks' status on IntegrationJob

config/manager/manager.yaml, controllers/configmap_controller.go, controllers/ingress_controller.go, main.go
Config can be configured dynamically without restarting the pod
Closes #55
=> [feat] Move config from cli args to configMap

Dockerfile, Makefile, api/v1/approval_types.go, api/v1/custom_tasks.go, config/apiservice/apiservice.yaml, config/crd/bases/cicd.tmax.io_approvals.yaml, config/manager/manager.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/release.yaml, controllers/customs/approval_run_controller.go, controllers/ingress_controller.go, controllers/integrationconfig_controller.go, controllers/integrationjob_controller.go, go.sum, hack/release-manifest.sh, internal/wrapper/wrapper.go, main.go, pkg/apiserver/apis/add_v1.go, pkg/apiserver/apis/apis.go, pkg/apiserver/apis/v1/apis.go, pkg/apiserver/apis/v1/approvals.go, pkg/apiserver/apis/v1/authorize.go, pkg/apiserver/apis/v1/decision.go, pkg/apiserver/cert.go, pkg/apiserver/server.go, pkg/pipelinemanager/approval_run.go, pkg/pipelinemanager/pipelinemanager.go, pkg/scheduler/scheduler.go
Now a user can apporve/reject an Approval object via extension API server (API aggregation).
close #37
=> [feat] Add api-server for Approval

api/v1/approval_types.go, config/crd/bases/cicd.tmax.io_approvals.yaml, config/manager/manager.yaml, config/rbac/role.yaml, config/release.yaml, controllers/approval_controller.go, controllers/customs/approval_run_controller.go, controllers/integrationconfig_controller.go, main.go, pkg/apiserver/apis/v1/decision.go
=> [feat] Add Role/RoleBinding for Approval's child

api/v1/approval_types.go, api/v1/integrationconfig_types.go, config/crd/bases/cicd.tmax.io_approvals.yaml, config/release.yaml, controllers/approval_controller.go, controllers/customs/approval_run_controller.go, controllers/integrationconfig_controller.go, controllers/integrationjob_controller.go, pkg/apiserver/apis/v1/decision.go, pkg/apiserver/server.go, pkg/scheduler/scheduler.go, pkg/server/handler_report.go, pkg/server/handler_webhook.go
=> [fix] Use patch instead of update in controllers

docs/installation.md
Fix #53 by a guide, instead of coding it
=> [doc] Update install guide

api/v1/integrationconfig_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/cicd.tmax.io_integrationconfigs.yaml, config/release.yaml, controllers/integrationconfig_controller.go
=> [feat] Add secrets field for IntegrationConfig

pkg/git/git.go, pkg/git/github/github.go, pkg/git/github/webhook.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/webhook.go, pkg/git/http.go, pkg/git/webhook_types.go, pkg/pipelinemanager/pipelinemanager.go
Closes #70
Also, fixed some bugs
=> [feat] Add state and action field for pull request webhook

controllers/integrationconfig_controller.go, controllers/integrationjob_controller.go, pkg/git/git.go, pkg/git/github/github.go, pkg/git/github/webhook.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/webhook.go, pkg/git/webhook_types.go, pkg/pipelinemanager/pipelinemanager.go
=> [feat] Delete webhook when IntegrationConfig is deleted

api/v1/integrationconfig_types.go, api/v1/integrationjob_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/cicd.tmax.io_integrationconfigs.yaml, config/crd/bases/cicd.tmax.io_integrationjobs.yaml, config/release.yaml, pkg/pipelinemanager/pipelinemanager.go
=> [feat] Add workspace support

api/v1/approval_types.go, api/v1/job_types.go, config/crd/bases/cicd.tmax.io_approvals.yaml, config/crd/bases/cicd.tmax.io_integrationconfigs.yaml, config/crd/bases/cicd.tmax.io_integrationjobs.yaml, config/release.yaml, controllers/approval_controller.go, controllers/customs/approval_run_controller.go, pkg/pipelinemanager/pipelinemanager.go
=> [fix] Fix default value issue for bool

api/v1/integrationjob_types.go, config/crd/bases/cicd.tmax.io_integrationjobs.yaml, config/release.yaml, pkg/pipelinemanager/approval_run.go
=> [feat] Add sender field to IntegrationJob

controllers/integrationjob_controller.go, pkg/scheduler/pool/pool.go
=> [feat] Handle IntegrationJob deletion

pkg/dispatcher/dispatcher.go
=> [feat] Add sender field for IntegrationJob

pkg/git/github/github.go, pkg/git/github/webhook.go
=> [fix] Fix github tag parse bug

Dockerfile, config/manager/manager.yaml, config/release.yaml, controllers/configmap_controller.go, controllers/ingress_controller.go, internal/configs/configs.go, internal/logrotate/logrotate.go, main.go
- Added ingress class addition feature
- Fixed log rotation bug
=> [fix] Fix hypercloud-integration bugs

docs/swagger-api.yaml
=> [doc] Add swagger API for Approvals

Makefile, config/release.yaml
Let's make sure we bump the Makefile's version before release
=> [chore] Bump release.yaml to v0.1.3

pkg/chatops/handlers_test.go, pkg/dispatcher/dispatcher.go
- Also, added test code for chat ops
=> [fix] Add labels for IntegrationJob

pkg/events/events.go, pkg/events/events_test.go, pkg/pipelinemanager/pipelinemanager.go
=> [feat] Emit events when IntegrationJob state is changed

README.md
=> test for integration config

internal/apiserver/apiserver.go, internal/apiserver/authorize.go
=> [fix] Fix user group header key

api/v1/git_types.go, api/v1/integrationjob_types.go, config/crd/bases/cicd.tmax.io_integrationjobs.yaml, config/release.yaml, controllers/customs/customs.go, controllers/customs/customs_test.go, controllers/customs/email_run_controller.go, controllers/customs/slack_run_controller.go, controllers/customs/slack_run_controller_test.go, docs/notification-jobs.md, pkg/apiserver/apis/v1/integrationconfigs/run_test.go, pkg/dispatcher/dispatcher.go, pkg/pipelinemanager/env.go
Fixed ref to a custom type and implemented GetTag and GetBranch methods
=> [feat] Support template for notification messages

pkg/git/git.go, pkg/git/github/github.go, pkg/git/github/github_types.go, pkg/git/github/parser.go, pkg/git/github/webhook.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_types.go, pkg/git/gitlab/parser.go, pkg/git/gitlab/webhook.go, pkg/git/webhook_types.go
- Add GetPullRequest methods
- Add ListCommitStatuses methods
- Add Labels field for PullRequest
=> [feat] Update git client

api/v1/integrationconfig_types.go, api/v1/merge_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/cicd.tmax.io_integrationconfigs.yaml, config/release.yaml, docs/merger.md, pkg/git/github/github.go, pkg/git/github/webhook.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_types.go, pkg/git/webhook_types.go
Added mergeConfig field to IntegrationConfig's spec field.
For merge automation feature, added mergeable fields for github/gitlab's
pull request structs.
=> [feat] Enable mergeConfig for IntegrationConfig

pkg/git/git.go, pkg/git/github/github.go, pkg/git/github/github_test.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_test.go, pkg/git/http.go, pkg/git/linkparser.go, pkg/git/linkparser_test.go
=> [feat] Enable pagination for git clients

pkg/apiserver/apis/v1/integrationconfigs/run.go, pkg/blocker/sync_pool_test.go, pkg/dispatcher/dispatcher.go, pkg/git/github/github.go, pkg/git/github/parser.go, pkg/git/github/webhook.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_types.go, pkg/git/gitlab/parser.go, pkg/git/webhook_types.go
=> [fix] Add base SHA to IntegrationJob for PreSubmit jobs

pkg/pipelinemanager/pipelinemanager.go
close #203 
Use pipeline run's message for the IntegrationJob's status and use
simple message for setting commit statuses
=> [fix] Set simple message only for commit status

pkg/blocker/checks.go, pkg/blocker/checks_test.go
Handle the case when the required commit status is not reported yet
=> [fix] Fix status check logic

api/v1/git_types.go, controllers/customs/slack_run_controller_test.go, internal/utils/utils.go, pkg/blocker/checks_test.go, pkg/blocker/sync_pool_test.go, pkg/blocker/sync_status.go, pkg/blocker/sync_status_test.go, pkg/git/fake/fake.go, pkg/git/git.go, pkg/git/github/github.go, pkg/git/github/github_types.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_types.go, pkg/git/gitlab/webhook.go, pkg/git/webhook_types.go, pkg/pipelinemanager/pipelinemanager.go
- Implement AddLabel/DeleteLabel methods
- Change SetCommitStatus interface
- Implement fake git client for testings
- (For GitLab) Get iid of merge request
=> [fix] Improve git clients

api/v1/merge_types.go, config/crd/cicd.tmax.io_integrationconfigs.yaml, config/release.yaml, controllers/configmap_controller.go, docs/integration_config.md, pkg/blocker/checks_test.go, pkg/blocker/sync_pool_test.go, pkg/blocker/sync_status_test.go, pkg/chatops/plugins/approve/handlers_approve_test.go, pkg/git/fake/fake.go, pkg/git/git.go, pkg/git/git_types.go, pkg/git/github/github.go, pkg/git/github/github_types.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_types.go, pkg/git/gitlab/parser.go
- Implemented GetBranch method of git clients
- Implemented MergePullRequest method of git clients
- Fixed some methods of fake git client
=> [feat] Add GetBranch, MergePullRequest methods to git clients

api/v1/git_types.go, api/v1/git_types_test.go, api/v1/merge_types.go, config/crd/cicd.tmax.io_integrationconfigs.yaml, config/release.yaml, docs/integration_config.md, pkg/blocker/blocker.go, pkg/blocker/checks.go, pkg/blocker/checks_test.go, pkg/blocker/merge.go, pkg/blocker/merge_test.go, pkg/blocker/status_server.go, pkg/blocker/status_server_test.go, pkg/blocker/sync_pool.go, pkg/blocker/sync_status.go, pkg/chatops/plugins/trigger/handlers_trigger.go, pkg/dispatcher/dispatcher.go, pkg/git/fake/fake.go, pkg/git/github/github.go, pkg/git/github/github_types.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_types.go, pkg/git/gitlab/parser.go, pkg/pipelinemanager/env.go, pkg/pipelinemanager/pipelinemanager.go, pkg/pipelinemanager/pipelinemanager_test.go
close #11
- Implemented prototype of merge automator
- Fixed some check logics
- Implemented a web server for fetching merge pool status
(As a blocker will be running in a separated binary)
- Removed redundant error return from dispatcher, pipelinemanager
`Docs will be written when the behavior of the blocker is fixed and stabilized`
=> [feat] Implement merge automation

cmd/controller/main.go, config/controller/controller.yaml, config/release.yaml, config/templates/email.yaml, config/templates/resport.yaml, controllers/configmap_controller.go, controllers/configmap_controller_test.go, internal/configs/blocker.go, internal/configs/blocker_test.go, internal/configs/configs.go, internal/configs/configs_test.go, internal/configs/controller.go, internal/configs/controller_test.go, pkg/collector/collector.go
close #214
- Decoupled configmap controller and controller main
- This is a prerequisite of blocker binary
=> [fix] Improve configmap controller

docs/README.md, docs/config_blocker.md, pkg/blocker/checks.go, pkg/blocker/checks_test.go, pkg/blocker/merge.go, pkg/blocker/merge_test.go
- Enabled global merge block label
- Enabled global merge method labels
- Fixed some test codes to use sub-test
=> [fix] Enable global merge configs

config/controller/controller.yaml, config/release.yaml, docs/configs.md, internal/configs/controller.go, pkg/pipelinemanager/step_git_checkout.go
Replace hard-coded git image to configurable variable
=> [fix] Make git image configurable

Makefile, build/blocker/Dockerfile, cmd/blocker/main.go, config/blocker/blocker.yaml, config/release.yaml, docs/integration_config.md, docs/modules/blocker.md, hack/release-manifest.sh
- Now merge automation feature is available
=> [feat] Enable merge automation

Makefile, config/release.yaml, docs/installation.md, hack/release-manifest.sh
=> [chore] Bump version to v0.3.0

.github/workflows/main.yaml, build/blocker/Dockerfile, build/controller/Dockerfile, cicd.yaml
=> [ci] Update CI configs

config/crd-key-mapping/cicd.tmax.io_approvals.yaml, config/crd-key-mapping/cicd.tmax.io_integrationconfigs.yaml, config/crd-key-mapping/cicd.tmax.io_integrationjobs.yaml
Add CRD file for i18n
IMS#264388
=> [chore] Add CRD for i18n

Makefile, config/release.yaml, docs/installation.md
=> [chore] Bump version to v0.3.1

cmd/blocker/main.go, cmd/controller/main.go, config/blocker/blocker.yaml, config/controller/controller.yaml, config/release.yaml, docs/installation.md
=> [fix] Add health and readiness probe to pods

docs/configs.md
Add `ingressHost` and `reportRedirectUriTemplate` option to the document
=> [docs] Add missing fields

cicd.yaml
Add email notification and mergeConfig for cicd.yaml
=> [chore] Add email notification and mergeConfig for cicd.yaml

Makefile, config/release.yaml, docs/development/release.md, docs/installation.md
=> [chore] Bump version to v0.3.2

api/v1/integrationjob_types.go, api/v1/zz_generated.deepcopy.go, config/crd/cicd.tmax.io_integrationjobs.yaml, config/release.yaml, docs/env.md, pkg/apiserver/apis/v1/integrationconfigs/run_test.go, pkg/blocker/merge.go, pkg/chatops/plugins/trigger/handlers_trigger.go, pkg/dispatcher/dispatcher.go, pkg/dispatcher/dispatcher_test.go, pkg/pipelinemanager/custom_runs.go, pkg/pipelinemanager/env.go, pkg/pipelinemanager/env_test.go, pkg/pipelinemanager/pipelinemanager.go, pkg/pipelinemanager/step_git_checkout.go
Alter 'Pull' to 'Pulls' in IntegrationJobRefs.
Before this commit, we handle only one Pull Request (PR) in
IntegrationJob. But we need to test multiple PRs at once because of
reducing time for re-testing.
As a result, this feature is to support the batch test(not implement
yet) in blocker.
=> [feat] Support multiple PRs in IntegrationJob

pkg/git/github/github_types.go, pkg/git/gitlab/gitlab_types.go
With the empty value, (for github) commit messages are lost
=> [fix] Request merge without title, message field if they're empty

cmd/controller/main.go, config/controller/controller.yaml, config/release.yaml, docs/plugins/size.md, internal/configs/plugins.go, internal/configs/plugins_test.go, pkg/plugins/size/size.go, pkg/plugins/size/size_test.go
close #237
Size plugin measures the size of a pull request, regarding the number of
changed lines in the pull request, and label the size tag to the pull
request.
=> [feat] Add size plugin

docs/config_blocker.md
=> [docs] Fix blocker configuration docs

controllers/customs/approval_run_controller.go, controllers/customs/approval_run_controller_test.go
close #255
This commit copies Approval's sending-email status, which is
non-critical but still informational, to Run's status.
=> [fix] Copy Approval status to Run status

internal/utils/restclient.go, internal/utils/restclient_test.go
Add group-version-resource specific rest client
Prerequisite of #250
=> [feat] Add resource-specific rest client

docs/integration_job.md
Update IntegrationJob document
=> [docs] Fix IntegrationJob document

Makefile
Now makefile has target to get overall coverage of the tests
=> [test] Add test coverage target to Makefile

docs/env.md, pkg/pipelinemanager/env.go, pkg/pipelinemanager/env_test.go
close #267
Added sender name/email env.s to jobs
=> [feat] Add sender environment variable

pkg/blocker/blocker.go, pkg/blocker/merge.go, pkg/blocker/merge_test.go
close #271
We give some time for github/gitlab to re-calculate PRs' mergeabilities.
Also, we try some times for merging a PR, for some cases where the
calculation takse long time
=> [fix] Try to merge a PR n-times

Makefile, config/release.yaml
=> [chore] Bump version to v0.4.0

config/crd-key-mapping/cicd.tmax.io_integrationconfigs.yaml, config/crd-key-mapping/cicd.tmax.io_integrationjobs.yaml
Updated to the latest CRD spec
=> [chore] Update i18n CRD manifests

controllers/expose_controller.go, controllers/expose_controller_test.go, pkg/pipelinemanager/step_git_checkout.go
Before this commit, watcher was not restarting when the watcher ends due
to the etcd's time limit. This commit fixes the issue.
=> [fix] Fix exposeController bug

Makefile, config/release.yaml
=> [chore] Bump version to v0.4.1

config/blocker/blocker.yaml, config/controller/controller.yaml, config/release.yaml
- Add docker.io for image urls
=> [chore] Add docker.io for image urls

controllers/expose_controller.go, controllers/expose_controller_test.go
=> [fix] Clean unnecessary logs

controllers/customs/approval_run_controller_test.go, controllers/customs/customs_test.go, controllers/customs/email_run_controller_test.go, controllers/customs/slack_run_controller.go, controllers/customs/slack_run_controller_test.go
- Implemented unimplemented test codes
- Improved test coverage for existing test codes
=> [test] Improve custom controllers' test coverage

go.sum, pkg/apiserver/apis/v1/approvals/decision.go, pkg/events/events.go
close #287 
When a user tries to approve/reject an approval, emits an event, even if
it fails to.
=> [feat] Emit events on approvals

cmd/blocker/main.go, cmd/controller/main.go, controllers/expose_controller.go, controllers/expose_controller_test.go, internal/configs/blocker.go, internal/configs/configs.go, internal/configs/controller.go
- Stop the world until the initial configmap reconcile is done
- Improve expose controller to avoid undesired errors
=> [fix] Wait until initial configmap reconcile

api/v1/integrationjob_types.go, api/v1/integrationjob_types_test.go, controllers/controllers_test.go, controllers/expose_controller_test.go, controllers/integrationconfig_controller.go, controllers/integrationconfig_controller_test.go, controllers/integrationjob_controller.go, controllers/integrationjob_controller_test.go, pkg/pipelinemanager/notification.go, pkg/pipelinemanager/pipelinemanager.go, pkg/scheduler/scheduler.go
- Added ic, ij's controller test codes
- Added test-purpose code blocks
- Refactored ic controller
- Refactored ij controller
- Changed PipelineManager to interface
=> [test] Add controller test codes for IC and IJ

config/controller/controller.yaml, config/release.yaml, docs/configs.md, internal/configs/controller.go, pkg/pipelinemanager/step_git_checkout.go, pkg/pipelinemanager/step_git_checkout_test.go
Now users can configure the checkout step's cpu, memory resource
=> [fix] Make checkout step's resource request configurable

cmd/controller/main.go, controllers/approval_controller.go, controllers/customs/email_run_controller.go, controllers/customs/email_run_controller_test.go, pkg/notification/mail/fake.go, pkg/notification/mail/fake_test.go, pkg/notification/mail/mail.go, pkg/notification/mail/mail_test.go
- Refactored email sender as an interface
- Added a fake email sender, which can be used for mock test
- Refactored email_run_controller's test code using the fake sender
=> [refactor] Refactor email sender

cmd/blocker/main.go, cmd/controller/main.go, controllers/configmap_controller.go, controllers/configmap_controller_test.go
Add configmap controller test codes
=> [test] Add configmap controller test codes

controllers/custom_run_controller_test.go
Add custom run controller's test code
=> [test] Add custom run controller's test code

controllers/approval_controller.go, controllers/approval_controller_test.go, controllers/integrationconfig_controller.go, controllers/integrationconfig_controller_test.go, pkg/git/fake/fake.go
Fix controller to add conditions' required fields
=> [fix] Fix controller to add conditions' required fields

cmd/blocker/main.go, cmd/controller/main.go, internal/configs/blocker_test.go, internal/configs/configs_test.go, internal/configs/controller_test.go, internal/logrotate/logrotate.go, internal/logrotate/logrotate_test.go, internal/utils/k8s.go, internal/utils/k8s_test.go, internal/utils/rand_test.go, internal/utils/response_test.go, internal/utils/restclient_test.go, internal/utils/utils.go, internal/utils/utils_test.go
=> [test] Add internal's test codes

Makefile, config/release.yaml
=> [chore] Bump version to v0.5.0

pkg/cron/cron.go
=> [bugfix] Fix incorrect logr usage

examples/14-periodic-job-using-tekton-task.yaml
=> [chore] Add periodic example

api/v1/integrationconfig_types_test.go, docs/integration_config.md, pkg/dispatcher/dispatcher_test.go
- Add test code & modify ic docs
=> [test] Add timeout related test code

config/blocker/blocker.yaml, config/controller/controller.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, config/release.yaml, hack/release-manifest.sh
Create cicd-service account and use it instead of default sa
=> [chore] Avoid using default service account

api/v1/integrationjob_types_test.go
Add test codes for tekton param converting functions
=> [test] Add tekton param test

docs/integration_config.md, examples/15-job-using-tekton-when.yaml
- Updated integration_config.md for conditional execution
- Added conditional execution example manifest
=> [chore] Update integration_config.md

Makefile, config/release.yaml
=> [chore] Bump version to v0.5.1

controllers/expose_controller.go, controllers/expose_controller_test.go
Fix ingress's annotation nil error
=> [fix] Fix ingress annotation nil error

api/v1/integrationconfig_types_test.go, api/v1/integrationjob_types_test.go, pkg/pipelinemanager/pipelinemanager.go, pkg/pipelinemanager/pipelinemanager_test.go
Add getParams method to avoid nil reference
=> [fix] Fix parameter get error

Makefile, config/release.yaml
=> [chore] Bump version to v0.5.2

controllers/integrationconfig_controller.go, controllers/integrationconfig_controller_test.go, pkg/git/fake/fake.go, pkg/git/github/github.go, pkg/git/github/github_test.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_test.go, pkg/git/http.go, pkg/git/http_test.go
Now integrationConfig registers the webhook after waiting for reset if the rate limit is exceeded when registering the webhook.
=> [feat] Handle the limit exceeds situations when registering webhook

docs/integration_config.md
Clarify integration config tektonWhen description
=> [chore] Fix integration_config.md

.github/workflows/v0.4.2.yaml
Add workflow for v0.4.2-release2
=> [chore] Fix github workflow

.github/workflows/main.yaml, config/rbac/role.yaml, config/release.yaml, controllers/integrationconfig_controller_test.go, controllers/integrationjob_controller.go, pkg/pipelinemanager/pipelinemanager.go, pkg/pipelinemanager/tektonTasks.go
- Now operator automatically mount service account token when using tekton tasks
=> [feat] Tekton task SA token mount

pkg/pipelinemanager/pipelinemanager.go
Fix inconsistency between integrationJob and taskRun when undefined error occurs
=> [fix] Fix task run condition sync with job state

.github/workflows/main.yaml, Makefile, config/release.yaml
- Add tekton task sa mount
- Fix integrationJob condition error
=> [chore] Bump version to v0.4.2-release3

.github/workflows/main.yaml
=> [chore] Workflow for v0.4.3 branch

cmd/webhook/main.go, docs/chat-commands.md, docs/integration_config.md, pkg/chatops/plugins/approve/handlers_approve.go, pkg/chatops/plugins/hold/handlers_hold.go, pkg/chatops/plugins/trigger/handlers_trigger.go, pkg/dispatcher/dispatcher.go, pkg/git/fake/fake.go, pkg/git/git.go, pkg/git/git_types.go, pkg/git/github/github.go, pkg/git/github/parser.go, pkg/git/github/webhook.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_types.go, pkg/git/gitlab/parser.go, pkg/git/gitlab/webhook.go, pkg/pipelinemanager/step_git_checkout.go
Now can use "/test" chat-ops from commit. Add "commit" to spec.jobs.postSubmit.when.branch of target jobs to use this function
=> [feat] Enable commit comment chat-ops

controllers/integrationconfig_controller.go, controllers/integrationconfig_controller_test.go, pkg/dispatcher/dispatcher.go, pkg/git/fake/fake.go, pkg/git/github/github.go, pkg/git/github/github_test.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_test.go, pkg/git/http.go, pkg/git/http_test.go
Removed incomplete git API limit logic.
=> [fix] Remove incomplete api limit logic

Makefile, config/release.yaml, go.mod, go.sum
=> [chore] Bump version to v0.5.3

pkg/git/git.go, pkg/git/github/github_test.go
=> [test] Add github test codes

pkg/pipelinemanager/pipelinemanager.go
- Fix unable to sync IJ.status with taskrun.status 
- Synchronization takes place only when taskRun.status.condition is either `true` or `false`
- remove status.CompletionTime when checking status
=> [fix] Fix taskrun status sync with IJ status

pkg/pipelinemanager/step_git_checkout.go
fix self-signed gitlab conection error
=> [Fix] support git insecure option

pkg/dispatcher/dispatcher.go, pkg/git/git_types.go, pkg/git/github/parser.go, pkg/git/gitlab/parser.go, pkg/pipelinemanager/env.go
requestBody is now observable in taskRun Pod when integrationConfig.Spec.ReqeustBodyLogging is set true
=> [Feat] support logging requestbody in taskRun pod

cmd/blocker/main.go, cmd/controller/main.go, docs/installation.md
=> [chore] enable to set log level

internal/configs/controller.go, pkg/pipelinemanager/step_git_checkout.go
fetch `GitCheckoutStepCPURequest` and `GitCheckoutStepMemRequest` from config and override default value if specified.
=> [fix] OOM kill during  git-checkout

.github/workflows/main.yaml
=> [fix] golangci workflow

api/v1/integrationconfig_types.go, config/crd/cicd.tmax.io_integrationconfigs.yaml, docs/integration_config.md, pkg/server/handler_webhook.go
원본 PR : https://github.com/tmax-cloud/cicd-operator/pull/356
- requestBodyLogging 오타 수정
pkg/server/handler_webhook.go, api/v1/integrationconfig_types.go, integration_config.md(v0.4.3 최신 커밋에서도 이 부분은 그렇게 되어있음)
이부분 reqeustBodyLogging를 requestBodyLogging로 수정
=> [feat] support logging requestbody

api/v1/integrationconfig_types.go, api/v1/zz_generated.deepcopy.go, config/crd/cicd.tmax.io_integrationconfigs.yaml, docs/integration_config.md, pkg/blocker/merge.go, pkg/dispatcher/dispatcher.go
v0.4 -> v0.5 merge
set default branch for jobs to be applied to : https://github.com/tmax-cloud/cicd-operator/commit/a3a1aeb50a53a04653a07b1e2b011ccb7833fc1a
fix fail to filter jobs : https://github.com/tmax-cloud/cicd-operator/commit/77a6a78ec141909863b1f4cb857b23e6f43c9aad
=> [feat] set default branch for jobs to be applied to

Makefile, go.mod, go.sum, pkg/pipelinemanager/custom_runs.go
=> [fix] unable to fetch variable when sending notification

Makefile, config/release.yaml, controllers/integrationjob_controller_test.go, go.mod, go.sum, pkg/pipelinemanager/pipelinemanager.go, pkg/pipelinemanager/pipelinemanager_test.go, pkg/scheduler/scheduler.go
create pipeline object if not exist
=> [feat] create pipeline if not exists

config/rbac/role.yaml
=> [fix] rbac for pipelines

config/rbac/role.yaml, config/release.yaml, controllers/integrationjob_controller.go
=> [fix] rbac for pipeline

Makefile, api/v1/git_types.go, config/crd/cicd.tmax.io_integrationconfigs.yaml, config/release.yaml, internal/utils/utils.go, pkg/git/gitea/gitea.go, pkg/git/gitea/gitea_type.go, pkg/git/gitea/parser.go, pkg/git/gitea/webhook.go
=> [feat] add gitea

Makefile, api/v1/git_types.go, config/release.yaml
=> [chore] bump up version to v0.6.0

Makefile, config/release.yaml, pkg/dispatcher/dispatcher.go
modify func matchString in dispatcher
ims issue number : 294768
=> [fix] modify func matchString in dispatcher

config/crd/cicd.tmax.io_approvals.yaml, config/crd/cicd.tmax.io_integrationconfigs.yaml, config/crd/cicd.tmax.io_integrationjobs.yaml, config/release.yaml, go.mod, go.sum
=> [fix] notification rollback

Makefile, config/release.yaml, controllers/integrationjob_controller.go, pkg/scheduler/scheduler.go
- [IMS-299758] ij 삭제 시 pipeline 리소스는 삭제되지 않는 이슈
- pipeline의 ownerreferences를 ij에 맵핑
=> [Fix] mapping ownerreferences of pipeline to ij
