Makefile
config/crd/bases/cicd.tmax.io_integrationconfigs.yaml
config/crd/bases/cicd.tmax.io_integrationjobs.yaml

- Unable to apply CRD yamls with following errors   
```
The CustomResourceDefinition "integrationconfigs.cicd.tmax.io" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[jobs].properties[postSubmit].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[jobs].properties[preSubmit].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```
- kubernetes-sigs/controller-tools#444
- Update controller-gen to v0.4.1, which includes temporary solution …

[build] Update controller-gen to v0.4.1

---

pkg/pipelinemanager/pipelinemanager.go
pkg/scheduler/fifo.go
pkg/scheduler/scheduler.go

- Check if 'running' jobs are actually running, inside scheduler
- Remove patching logic for IntegrationJob after scheduling, because
there would be no timing skew with the explicit running-check logic
- Add secondary order policy (alphanumerical) for sorting pending jobs
- Add minimum time gap between two scheduling events
- Mainly part of #8 
- Also affects #9

[fix] Improve scheduler logic

---

pkg/git/github/webhook.go

- Current
* Repository name is `cicd-operator` for `cqbqdd11519/cicd-operator`
- Fixed
* Repository name is `cqbqdd11519/cicd-operator` for `cqbqdd11519/cicd-operator`

[fix] Fix to use full_name rather than name for repository name

---

controllers/integrationjob_controller.go
go.mod
go.sum
pkg/scheduler/fifo.go
pkg/scheduler/pool/pool.go
pkg/scheduler/pool/pool_test.go
pkg/scheduler/scheduler.go
pkg/structs/queue.go
pkg/structs/queue_test.go

Added JobPool, which is a kind of in-memory cache for IntegrationJobs,
in status of pending or running.
This JobPool is synced whenever the status of IntegrationJobs change.
Scheduling logic is called for only three following cases.
1. New IntegrationJob is generated
2. Existing IntegrationJob is deleted
3. Running IntegrationJob is completed/failed
Then the scheduler reads the pool and creates new PipelineRun when there
exists fewer PipelineRuns than the maximum number.
#8 #14

[fix] Modify scheduling logic

---

pkg/collector/collector.go

- Reconfigure only when the spec is changed
- Run collect function once when it is reconfigured

[fix] Fix collector bug

---

controllers/integrationconfig_controller.go

Now finalizer is deleted even if error occurred while deleting webhook from git server

[fix] Fix finalizer handling logic for IntegrationConfig

---

pkg/chatops/errors.go
pkg/chatops/handlers.go
pkg/git/git.go
pkg/git/github/github.go
pkg/git/github/github_types.go
pkg/git/github/webhook.go
pkg/git/gitlab/gitlab.go
pkg/git/gitlab/gitlab_types.go

- Register 'Unauthorized' message comment if chat-ops sender is not an author of the pull request and does not have write permission on the repository

[feat] Add feedback comment for chat-ops

---

config/manager/manager.yaml
config/release.yaml
controllers/configmap_controller.go
controllers/ingress_controller.go
internal/configs/configs.go
main.go

Ingress controller was originally meant to make sure an ingress for the
webhook server is ready before running the server.
Now it reconciles Ingress so that it can handle the change of the
Ingress while operating.

[fix] Change ingress controller as a real controller

---

api/v1/git_types.go
docs/integration_config.md
pkg/apiserver/apis/v1/integrationconfigs/integrationconfigs.go
pkg/apiserver/apis/v1/integrationconfigs/run.go
pkg/apiserver/apis/v1/integrationconfigs/run_test.go
pkg/apiserver/apis/v1/v1.go
pkg/git/git.go
pkg/git/github/github.go
pkg/git/gitlab/gitlab.go
pkg/pipelinemanager/step_git_checkout.go
pkg/server/handler_webhook.go
pkg/server/plugin.go

- Added api set (/runpre, /runpost) to IntegrationConfig so that users
can trigger the jobs manually, not via git events.

[feat] Enable manual trigger of IntegrationConfig's jobs

---

Makefile
cmd/cicdctl/approve/approve.go
cmd/cicdctl/main.go
cmd/cicdctl/run/run.go
controllers/suite_test.go
docs/approval.md
docs/cicdctl.md
docs/integration_config.md
go.mod
go.sum
pkg/cli/cli.go
pkg/cli/configs.go
pkg/cli/kubeconfig.go

cicdctl makes it easier to call extension apis, such as
approving/rejecting an approval, or triggering jobs of
IntegrationConfigs.
Refer to the docs and help command for the further usage

[feat] Implement cicdctl, a CLI tool

---

pkg/blocker/blocker.go
pkg/blocker/checks.go
pkg/blocker/checks_test.go
pkg/blocker/sync_pool.go
pkg/blocker/sync_pool_test.go

- Use APIURL/repo as a key for synchronizing PR pools, instead of using
Namespace/Name of an IntegrationConfig
- Enabled to loop sync periodically
- Refactored blocker's common structures
- Fix label check bug

[fix] Change key for synchronizing pull request pools

---

pkg/pipelinemanager/pipelinemanager.go
pkg/pipelinemanager/pipelinemanager_test.go

close #189 
Base SHA is added to the commit statuses' descriptions (only for pull
requests).
It can be used to check if tests are done against the most recent commit
of the target branch before the pull request being merged.

[feat] Add base sha for commit status description

---

docs/blocker.md
pkg/blocker/blocker.go
pkg/blocker/blocker_test.go
pkg/blocker/checks.go
pkg/blocker/checks_test.go
pkg/blocker/sync_pool.go
pkg/blocker/sync_pool_test.go
pkg/blocker/sync_status.go
pkg/blocker/sync_status_test.go

Every time pool syncer finishes it's job, status syncer starts a job to
synchronize PRs' status.
It checks if PRs in a merge pool is ready to be merged (i.e., meets all
the conditions including commit statuses and merge conflict).
Also, it reports blocker's status (e.g., in-merge-pool, not-mergeable)
to the PRs. It is done for every PRs including those who are not in the
merge pool.

[feat] Add status syncer to blocker

---

pkg/blocker/merge.go

- This commit avoids errors when the merge method is not set properly.
- Document (/docs/integration_config.md#method) says default value for
the method is `merge`.

[fix] Set default merge method as 'merge'

---

pkg/apiserver/apis/v1/integrationconfigs/run.go
pkg/blocker/checks.go
pkg/blocker/checks_test.go
pkg/blocker/merge.go
pkg/blocker/sync_pool_test.go
pkg/chatops/plugins/approve/handlers_approve.go
pkg/chatops/plugins/approve/handlers_approve_test.go
pkg/chatops/plugins/trigger/handlers_trigger.go
pkg/chatops/plugins/trigger/handlers_trigger_test.go
pkg/dispatcher/dispatcher.go
pkg/git/fake/fake.go
pkg/git/git_types.go
pkg/git/github/github.go
pkg/git/github/parser.go
pkg/git/github/webhook.go
pkg/git/gitlab/gitlab.go
pkg/git/gitlab/parser.go

In the case of pull-request edit, such as labelling and unlabelling,
webhook's sender is different from the pull request's author.
To authorize labelling/unlabelling event (#226), we should know the
exact sender (who actually labelled the pull request), not the author of
the pull request.
This commit differentiates webhook sedner and pull request author. In
addition, authors of issue comments are differentiated as well.

[fix] Differentiate webhook sender and pull request author

---

pkg/blocker/blocker.go
pkg/blocker/sync_pool.go

Before this commit, when a new commit is added to the pull request,
commit status of blocker to the pull request is not set until conditions
change, because the cache is treated 'not dirty'.
This commit fixes the issue, by setting the cache is dirty when the SHA
changes for the pull request.

[fix] Invalidate pr pool cache if new commit is added

---

cmd/controller/main.go
docs/quickstart.md
pkg/chatops/plugins/approve/handlers_approve.go
pkg/git/git_types.go
pkg/git/github/parser.go
pkg/git/github/webhook.go
pkg/git/gitlab/parser.go
pkg/git/gitlab/webhook.go

close #226
This commit prevents an author of a pull request to approve his/her own
pull request.
FYI) If a bot account makes pull requests, race can happen for
'approved' label. (label -> unlabel -> label -> ...)

[fix] Authorize setter of 'approved' label

---

go.mod
go.sum
pkg/chatops/plugins/approve/handlers_approve.go
pkg/chatops/plugins/approve/handlers_approve_test.go

Approval plugin was misconfigured to check 'issue_comment' type event on
approval/reject via github/gitlab's approval system.
This commit corrects it to check 'pull_request_review' and adds
additional log for approval plugin

[fix] Change approval plugin's target event type

---

controllers/approval_controller.go

IMS#265146 Action#1635274
Approval sender's name can be unicode, which is not supported in labels.
To avoid an error which role/rolebinding is not created, this commit
sets sender's name as annotation, not label.

[fix] Set approval sender name as annotation, not label

---

cmd/controller/main.go
docs/chat-commands.md
docs/plugins/hold.md
internal/configs/blocker.go
internal/configs/blocker_test.go
pkg/chatops/plugins/hold/handlers_hold.go
pkg/chatops/plugins/hold/handlers_hold_test.go

close #243
This commit implements hold plugin. Anyone can hold a pull request from
being merged by commenting '/hold' and can cancel the hold by commenting
'/hold cancel'.
Also, default hold label is changed to ci/hold

[feat] Add hold plugin

---

pkg/blocker/merge.go
pkg/blocker/merge_test.go
pkg/git/github/parser.go

close #215 
Previously, only one PR can be tested before block-merge.
Now we can test multiple PRs at once by creating IntegrationJob.
Add the field "Sender" to git.PullRequest which be used to create ij.

[feat] Support batch test using IntegrationJob

---

api/v1/approval_types.go
controllers/approval_controller.go
controllers/customs/approval_run_controller.go
controllers/customs/approval_run_controller_test.go
controllers/customs/email_run_controller.go
controllers/customs/slack_run_controller.go

This commit changes all 'Waiting' statues to 'Awaiting' statuses, to
meet the consensus for such statuses in HyperCloud (UX)

[fix] Change Waiting status to Awaiting status

---

api/v1/merge_types.go
config/crd/cicd.tmax.io_integrationconfigs.yaml
config/release.yaml
docs/integration_config.md
pkg/blocker/blocker.go
pkg/blocker/merge.go
pkg/blocker/merge_test.go
pkg/git/fake/fake.go
pkg/git/gitlab/gitlab.go

close #265
If commit template is specified in the IntegrationConfig's mergeConfig,
the template is compiled using blocker.PullRequest struct.
Before compiling it, commits of the pull request is parsed and set to
the structure's Commit field.
User can use the PR's info and commits for writing the message temaplte.
Also, fake git client's MergePullRequest method is implemented. As a
result, there are some modifications in the test codes.

[feat] Enable merge commit template

---

pkg/apiserver/apis/v1/integrationconfigs/run.go
pkg/chatops/chatops.go
pkg/chatops/plugins/approve/handlers_approve.go
pkg/dispatcher/dispatcher.go
pkg/plugins/size/size.go
pkg/server/plugin.go

Before this commit, every plugins were called so that if we call
runPre api, size plugin is called so that it occurs an git api error.
To solve this, we call only dispatcher plugin on api calls

[fix] Trigger only dispatcher plugin for run api

---

controllers/integrationconfig_controller.go

Fix the problem that occurs when deleting "integrationConfig"
and re-creating it while the controller is still running.

[bugfix] Fix the incorrect conditional statement

---

pkg/dispatcher/dispatcher.go

when both `ic.when` and `job.when` are specified, it fails to filter jobs, resulting in no `taskRun`

[Fix] fail to filter jobs

---

pkg/dispatcher/dispatcher.go
pkg/git/git_types.go
pkg/git/github/parser.go
pkg/git/gitlab/parser.go
pkg/pipelinemanager/env.go

v0.4 -> v0.5 merge
[Feat] support logging requestbody in taskRun pod : https://github.com/tmax-cloud/cicd-operator/pull/364
requestBody is now observable in taskRun Pod when integrationConfig.Spec.ReqeustBodyLogging is set true

[Feat] support logging requestbody in taskRun pod
